{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import h5py\n",
    "from sklearn.cluster import KMeans\n",
    "from sklearn import metrics\n",
    "import numpy as np\n",
    "#import math\n",
    "#import random\n",
    "import heapq\n",
    "import matplotlib.pyplot as plt\n",
    "import random"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(190500, 1623)\n"
     ]
    }
   ],
   "source": [
    "filename = '/usr/local/home/yizhu/Desktop/BSLB_sample.h5'\n",
    "\n",
    "f = h5py.File(filename,'r+') \n",
    "print(f['traces'].shape)\n",
    "f.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(12750, 1000)\n"
     ]
    }
   ],
   "source": [
    "\n",
    "filename = '/usr/local/home/yizhu/Desktop/Yizhu/BFFile_withPython_save/cswap_pointer.h5'\n",
    "\n",
    "f = h5py.File(filename,'r+') \n",
    "data_ecc_pointer = f['attacking_data'][:,0]\n",
    "traces_ecc_pointer = f['attacking_traces']\n",
    "print(traces_ecc_pointer.shape)\n",
    "f.close()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Cluster_k_means(object):\n",
    "\n",
    "    def __init__(self, traces, k, step):\n",
    "\n",
    "        self.found = 0  #iretation count\n",
    "        \n",
    "        self.step = step  #iretation limit\n",
    "        self.k = k\n",
    "        self.traces = traces\n",
    "        self.dim = self.traces.shape[1]\n",
    "\n",
    "        index_random = set() \n",
    "        while(len(index_random)<k):\n",
    "            index_random.add(random.randint(0,self.traces.shape[0]-1))\n",
    "        index_random = list(index_random)\n",
    "\n",
    "        self.guesses = [list(self.traces[index_random[i]]) for i in range(k)] #initial center\n",
    "\n",
    "        self.initial_convert_and_sort()\n",
    "\n",
    "    def initial_convert_and_sort(self):\n",
    "\n",
    "        self.traces = self.get_data(self.traces)\n",
    "        self.unpack_new_centers()\n",
    "\n",
    "    def get_data(self, traces): #classification by picking minimum distance\n",
    "        new_data = []\n",
    "\n",
    "        for trace in traces:\n",
    "            distances = []\n",
    "            for guess in self.guesses:\n",
    "                distance = math.sqrt(\n",
    "                    sum((trace[i] - guess[i])**2 for i in range(self.dim))\n",
    "                )\n",
    "                distances.append(distance)\n",
    "\n",
    "            ki = distances.index(min(distances))\n",
    "\n",
    "            d = {\n",
    "                \"ki\": ki,\n",
    "                \"trace\": trace\n",
    "            }\n",
    "            new_data.append(d)\n",
    "\n",
    "        return new_data\n",
    "    \n",
    "    def unpack_new_centers(self):  # update center\n",
    "        for ki, guess in enumerate(self.guesses):\n",
    "\n",
    "            traces = [d[\"trace\"] for d in self.traces if d[\"ki\"] == ki]\n",
    "            new_guess = []\n",
    "\n",
    "            if traces:\n",
    "                for i in range(self.dim):\n",
    "                    iguess = sum(trace[i] for trace in traces) / len(traces)\n",
    "                    new_guess.insert(i, iguess)\n",
    "\n",
    "                self.guesses[ki] = new_guess\n",
    "            else:\n",
    "                mini = lambda i: min(d[\"trace\"][i] for d in self.data)\n",
    "                maxi = lambda i: max(d[\"trace\"][i] for d in self.data)\n",
    "                self.guesses[ki] = [random.triangular(mini(i), maxi(i)) for i in range(self.dim)]\n",
    "\n",
    "        self.correspond_nearest()\n",
    "    \n",
    "    def correspond_nearest(self): # \n",
    "\n",
    "        traces = [d[\"trace\"] for d in self.traces]\n",
    "        new_data = self.get_data(traces)\n",
    "\n",
    "        if new_data == self.traces:\n",
    "            self.found += 1\n",
    "            if self.found >= self.step:\n",
    "                print (self.found)\n",
    "                return self.guesses\n",
    "            else:\n",
    "                self.unpack_new_centers()\n",
    "        else:\n",
    "            self.traces = new_data\n",
    "            self.unpack_new_centers()\n",
    "\n",
    "#mean_data = Cluster_k_means(f['traces'][:10],2,10).guesses\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [],
   "source": [
    "# compute sum-of-squared-t values\n",
    "\n",
    "class SOST():\n",
    "    def __init__(self, traces, labels):\n",
    "        self.traces = traces\n",
    "        self.trace_length = self.traces.shape[1]\n",
    "        self.trace_number= self.traces.shape[0]\n",
    "        self.lables = labels\n",
    "        self.classfication = 2\n",
    "        \n",
    "        indices = self.list_of_indices_per_classfication()\n",
    "        self.sost = self.sost_coefficients(indices)\n",
    "\n",
    "    def list_of_indices_per_classfication(self):\n",
    "\n",
    "        indices_list = []\n",
    "        for i in range(self.classfication):\n",
    "            indices_list.append([])\n",
    "            for j in range(self.trace_number):\n",
    "                if self.lables[j] == i:\n",
    "                    indices_list[i].append(j)\n",
    "\n",
    "        return indices_list\n",
    "    \n",
    "    def sost_coefficients(self, indices):\n",
    "        sost_coefficients = np.empty(self.trace_length)\n",
    "        for t in range(self.trace_length):\n",
    "            means = np.empty(self.classfication)\n",
    "            variances = np.empty(self.classfication)\n",
    "            counts = np.empty(self.classfication)\n",
    "            result = 0\n",
    "\n",
    "            for i in range(self.classfication):\n",
    "                values = self.traces[indices[i], t]\n",
    "                means[i] = np.mean(values)\n",
    "                variances[i] = np.var(values)\n",
    "                counts[i] = len(values)\n",
    "\n",
    "            if self.classfication == 2:\n",
    "                temp = pow(means[0] - means[1], 2)\n",
    "                temp /= variances[0]/counts[0] + variances[1]/counts[1]\n",
    "                result += temp\n",
    "            else: \n",
    "                print('only compute 2 classifications!')\n",
    "                return\n",
    "\n",
    "            sost_coefficients[t] = result\n",
    "\n",
    "        return sost_coefficients\n",
    "     "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# outlier detection\n",
    "\n",
    "def outlier_remove(data, traces, threshold):\n",
    "\n",
    "    means = traces.mean(0)\n",
    "    stds = traces.std(0)\n",
    "    traces_evl_value = (abs(traces-means)).sum(1) - (threshold * stds).sum()\n",
    "    traces_evl = traces_evl_value >= 0\n",
    "\n",
    "    outliers_index = [i for i in range(traces.shape[0]) if traces_evl[i]]\n",
    "    print('outlier number:', len(outliers_index))\n",
    "    print('outlier ratio:',len(outliers_index)/traces.shape[0])\n",
    "\n",
    "    traces_new = np.delete(traces, outliers_index, 0)\n",
    "    print('traces_new.shape:', traces_new.shape)\n",
    "\n",
    "    data_new = np.delete(data, outliers_index, 0)\n",
    "    print('data_new.shape:', data_new.shape)\n",
    "\n",
    "    return data_new, traces_new\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def outlier_replace(traces, threshold):\n",
    "\n",
    "    means = traces.mean(0)\n",
    "    stds = traces.std(0)\n",
    "    traces_evl_value = abs(traces-means) - threshold * stds\n",
    "    traces_evl = traces_evl_value > 0\n",
    "    \n",
    "    #means_evl = 1- traces_evl \n",
    "\n",
    "    #means_no_outliers = (traces * means_evl).mean(0)\n",
    "    for t in range(traces.shape[0]):\n",
    "        for i in range(traces.shape[1]):\n",
    "            if traces_evl[t][i]:\n",
    "                #traces[t][i] = means_no_outliers[i]\n",
    "                traces[t][i] = means[i]\n",
    "\n",
    "    print('outlier number:', traces_evl.sum())\n",
    "    print('outlier ratio:',traces_evl.sum()/(traces.shape[0]*traces.shape[1]))\n",
    "    print('traces_new.shape:', traces.shape)\n",
    "    return traces"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [],
   "source": [
    "def attampt(labels, traces, POI_numbers, steps,note):\n",
    "    # save results\n",
    "    data_save = np.empty((3,steps))\n",
    "\n",
    "    if len(POI_numbers) + 1 < steps:\n",
    "        raise ValueError\n",
    "\n",
    "    kmeans_cluster = KMeans(n_clusters=2, random_state=0).fit(traces)\n",
    "\n",
    "    kmeans_labels = kmeans_cluster.labels_ \n",
    "    #recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "    recovery_rate = (np.multiply((kmeans_labels == labels),1)).sum()/len(labels)\n",
    "    if recovery_rate < 0.5:\n",
    "        recovery_rate = 1 - recovery_rate\n",
    "\n",
    "    silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "    #print(f'step 1: recovery {recovery_rate}, Silhouette {silhouette_score}'  )\n",
    "\n",
    "    # save results\n",
    "    data_save[0,0] = str(traces.shape[1])\n",
    "    data_save[1,0] = str(recovery_rate)\n",
    "    data_save[2,0] = str(silhouette_score)\n",
    " \n",
    "    for i in range(steps-1):\n",
    "        sost_all = SOST(traces,kmeans_cluster.labels_).sost\n",
    "        POI_number = POI_numbers[i]\n",
    "\n",
    "        POI_indexs = np.argsort(-sost_all)[:POI_number]\n",
    "        traces_new = traces[ :,POI_indexs]\n",
    "        kmeans_cluster = KMeans(n_clusters=2, random_state=0).fit(traces_new)\n",
    "\n",
    "        kmeans_labels = kmeans_cluster.labels_ \n",
    "        #recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "        recovery_rate = (np.multiply((kmeans_labels == labels),1)).sum()/len(labels)\n",
    "        if recovery_rate < 0.5:\n",
    "            recovery_rate = 1 - recovery_rate\n",
    "\n",
    "        #silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "        silhouette_score = metrics.silhouette_score(traces_new, kmeans_labels, metric='euclidean')\n",
    "        #print(f'step {i+2}: recovery {recovery_rate}, Silhouette {silhouette_score}')\n",
    "\n",
    "        data_save[0,i+1] = str(POI_number)\n",
    "        data_save[1,i+1] = str(recovery_rate)\n",
    "        data_save[2,i+1] = str(silhouette_score)\n",
    "\n",
    "        if  POI_number == 1:\n",
    "            data_save[2,i+1] = POI_indexs\n",
    "\n",
    "\n",
    "    fmt = '%d', '%1.3f', '%1.3f'\n",
    "    np.savetxt(f\"ecc_pointer/multi-{traces.shape}-{note}-{steps}.txt\", data_save.T, fmt=fmt, delimiter=' ')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "def kmeans_single_dim(traces): \n",
    "    n_traces = traces.shape[0]\n",
    "    n_points = traces.shape[1]\n",
    "\n",
    "    labels = np.zeros((n_traces, n_points))\n",
    "    final_labels = np.zeros(n_traces)\n",
    "\n",
    "    # apply kmeans to all points of one timing, determine the label of each point\n",
    "    for i in range(traces.shape[1]):\n",
    "        kmeans_cluster = KMeans(n_clusters=2, random_state=0).fit(traces[:, i].reshape(-1, 1))\n",
    "        labels[:,i] = kmeans_cluster.labels_\n",
    "\n",
    "    # reference timing (one column), random choose(less meaning) or choose leakage \n",
    "    t = int(0.7 * n_points)\n",
    "    t = 0\n",
    "    reference_t = labels[:, t]\n",
    "\n",
    "    # flip it if one column is far different from the reference column\n",
    "    for i in range(n_points):\n",
    "        eval = labels[:, i] == reference_t\n",
    "        if eval.sum() < n_traces/2:\n",
    "            labels[:, i] = 1 - labels[:, i]\n",
    "\n",
    "    # majority rule to determine the label of each trace\n",
    "    for i in range(n_traces):\n",
    "        if list(labels[i]).count(1) > n_points / 2:\n",
    "            final_labels[i] = 1\n",
    "\n",
    "    return final_labels\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def attampt_single_dim(labels, traces, POI_numbers, steps, note):\n",
    "    # save results\n",
    "    data_save = np.empty((3,steps))\n",
    "\n",
    "    if len(POI_numbers) + 1 < steps:\n",
    "        raise ValueError\n",
    "\n",
    "    \n",
    "    kmeans_labels = kmeans_single_dim(traces)\n",
    " \n",
    "    recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "    if recovery_rate < 0.5:\n",
    "        recovery_rate = 1 - recovery_rate\n",
    "\n",
    "    silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "    #print(f'step 1: recovery {recovery_rate}, Silhouette {silhouette_score}'  )\n",
    "\n",
    "    # save results\n",
    "    data_save[0,0] = str(traces.shape[1])\n",
    "    data_save[1,0] = str(recovery_rate)\n",
    "    data_save[2,0] = str(silhouette_score)\n",
    "\n",
    "\n",
    "    for i in range(steps-1):\n",
    "        sost_all = SOST(traces,kmeans_labels).sost\n",
    "        POI_number = POI_numbers[i]\n",
    "\n",
    "        POI_indexs = np.argsort(-sost_all)[:POI_number]\n",
    "        traces_new = traces[ :,POI_indexs]\n",
    "        kmeans_labels = kmeans_single_dim(traces_new)\n",
    "\n",
    "        recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "        if recovery_rate < 0.5:\n",
    "            recovery_rate = 1 - recovery_rate\n",
    "\n",
    "        #silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "        ilhouette_score = metrics.silhouette_score(traces_new, kmeans_labels, metric='euclidean')\n",
    "        #print(f'step {i+2}: recovery {recovery_rate}, Silhouette {silhouette_score}'  )\n",
    "\n",
    "        data_save[0,i+1] = str(POI_number)\n",
    "        data_save[1,i+1] = str(recovery_rate)\n",
    "        data_save[2,i+1] = str(silhouette_score)\n",
    "\n",
    "    fmt = '%d', '%1.3f', '%1.3f'\n",
    "    np.savetxt(f\"single/single-{traces.shape}-{steps}-{note}.txt\", data_save.T, fmt=fmt, delimiter=' ')\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def attampt_single(labels, traces, POI_numbers, steps, note, labels_all):\n",
    "\n",
    "    data_save = np.empty((3,steps))\n",
    "\n",
    "    if len(POI_numbers) + 1 < steps:\n",
    "        raise ValueError\n",
    "    \n",
    "    n_traces = traces.shape[0]\n",
    "    n_points = traces.shape[1]\n",
    "\n",
    "    # reference timing (one column), random choose(less meaning) or choose leakage \n",
    "    random.seed(2023)\n",
    "    t = random.randint(0, n_points-1)\n",
    "    reference_t = labels_all[:, t]\n",
    "\n",
    "    kmeans_labels = labels_base_reference(reference_t, labels_all, n_points, n_traces)\n",
    "\n",
    "\n",
    "\n",
    "    recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "    if recovery_rate < 0.5:\n",
    "        recovery_rate = 1 - recovery_rate\n",
    "\n",
    "    silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "    #print(f'step 1: recovery {recovery_rate}, Silhouette {silhouette_score}'  )\n",
    "\n",
    "    # save results\n",
    "    data_save[0,0] = str(traces.shape[1])\n",
    "    data_save[1,0] = str(recovery_rate)\n",
    "    data_save[2,0] = str(silhouette_score)\n",
    "\n",
    "\n",
    "    for i in range(steps-1):\n",
    "        sost_all = SOST(traces,kmeans_labels).sost\n",
    "        POI_number = POI_numbers[i]\n",
    "\n",
    "        POI_indexs = np.argsort(-sost_all)[:POI_number]\n",
    "        traces_new = traces[ :,POI_indexs]\n",
    "        n_traces = traces_new.shape[0]\n",
    "        n_points = traces_new.shape[1]\n",
    "\n",
    "        t = random.randint(0, n_points-1)\n",
    "        reference_t = traces_new[:, t]\n",
    "\n",
    "        kmeans_labels = labels_base_reference(reference_t, labels_all[ :,POI_indexs], n_points, n_traces)\n",
    "\n",
    "        recovery_rate = (kmeans_labels == labels).sum()/len(labels)\n",
    "        if recovery_rate < 0.5:\n",
    "            recovery_rate = 1 - recovery_rate\n",
    "\n",
    "        #silhouette_score = metrics.silhouette_score(traces, kmeans_labels, metric='euclidean')\n",
    "        silhouette_score = metrics.silhouette_score(traces_new, kmeans_labels, metric='euclidean')\n",
    "        #print(f'step {i+2}: recovery {recovery_rate}, Silhouette {silhouette_score}'  )\n",
    "\n",
    "        data_save[0,i+1] = str(POI_number)\n",
    "        data_save[1,i+1] = str(recovery_rate)\n",
    "        data_save[2,i+1] = str(silhouette_score)\n",
    "\n",
    "    fmt = '%d', '%1.3f', '%1.3f'\n",
    "    np.savetxt(f\"single/random-{traces.shape}-{steps}-{note}.txt\", data_save.T, fmt=fmt, delimiter=' ')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "def labels_base_reference(reference_t, labels, n_points, n_traces):\n",
    "    final_labels = np.zeros(n_traces)\n",
    "\n",
    "    # flip it if one column is far different from the reference column\n",
    "    for i in range(n_points):\n",
    "        eval = labels[:, i] == reference_t\n",
    "        if eval.sum() < n_traces/2:\n",
    "            labels[:, i] = 1 - labels[:, i]\n",
    "\n",
    "    # majority rule to determine the label of each trace\n",
    "    for i in range(n_traces):\n",
    "        if list(labels[i]).count(1) > n_points / 2:\n",
    "            final_labels[i] = 1\n",
    "\n",
    "    return final_labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "attampt(f['data'][:10000], f['traces'][:10000], [300], 2, 300)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "POIs = [600 for i in range(8)]\n",
    "print(POIs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "attampt(f['data'][:10000], f['traces'][:10000], POIs, len(POIs)+1, '600')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "initial = 1623\n",
    "POIs = [initial]\n",
    "rate = 0.5\n",
    "for i in range(80):\n",
    "    POI = POIs[-1]\n",
    "    temp = int(POI * rate)\n",
    "    if temp > 0:\n",
    "        POIs.append(temp)\n",
    "        rate_temp = rate * 1.05\n",
    "        if rate_temp < 1:\n",
    "            rate = rate_temp\n",
    "    else:\n",
    "        continue        \n",
    "\n",
    "    if POIs:\n",
    "        attampt(f['data'][:10000], f['traces'][:10000], POIs, len(POIs)+1, f'{initial}-increasing rate')\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "initial = 1623\n",
    "POIs = [initial]\n",
    "rate = 0.9\n",
    "for i in range(80):\n",
    "    POI = POIs[-1]\n",
    "    temp = int(POI * rate)\n",
    "    if temp > 0:\n",
    "        POIs.append(temp)\n",
    "        rate_temp = rate * 1.1\n",
    "        if rate_temp < 1:\n",
    "            rate = rate_temp\n",
    "    else:\n",
    "        continue        \n",
    "\n",
    "    if POIs:\n",
    "        attampt(f['data'][:10000], f['traces'][:10000], POIs, len(POIs)+1, f'{initial}-increasing rate')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "initials = [1623]\n",
    "rates = [0.9]\n",
    "for initial in initials:\n",
    "    \n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(80):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(f['data'][:10000], f['traces'][:10000], POIs, len(POIs)+1, f'{initial}-{rate}-reference')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_result(data, traces, steps, memo):\n",
    "    attampt(data, traces, [500 for i in range(steps-1)], steps, f'500-{memo}')\n",
    "    attampt(data, traces, [400 for i in range(steps-1)], steps, f'400-{memo}')\n",
    "    attampt(data, traces, [300 for i in range(steps-1)], steps, f'300-{memo}')\n",
    "    attampt(data, traces, [200 for i in range(steps-1)], steps, f'200-{memo}')\n",
    "    attampt(data, traces, [150 for i in range(steps-1)], steps, f'150-{memo}')\n",
    "    attampt(data, traces, [100 for i in range(steps-1)], steps, f'100-{memo}')\n",
    "    attampt(data, traces, [70 for i in range(steps-1)], steps, f'70-{memo}')\n",
    "    attampt(data, traces, [50 for i in range(steps-1)], steps, f'50-{memo}')\n",
    "    attampt(data, traces, [30 for i in range(steps-1)], steps, f'30-{memo}')\n",
    "    attampt(data, traces, [20 for i in range(steps-1)], steps, f'20-{memo}')\n",
    "    attampt(data, traces, [10 for i in range(steps-1)], steps, f'10-{memo}')\n",
    "    attampt(data, traces, [5 for i in range(steps-1)], steps, f'5-{memo}')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 105,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "outlier number: 1234\n",
      "outlier ratio: 0.1234\n",
      "traces_new.shape: (8766, 1623)\n",
      "data_new.shape: (8766,)\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "data_no_outliers , traces_no_outliers = outlier_remove(f['data'][:10000], f['traces'][:10000],1)\n",
    "print('\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_result_no(data, traces, steps):\n",
    "    attampt(data, traces, [500 for i in range(steps-1)], steps, '500-no_outliers-1')\n",
    "    attampt(data, traces, [400 for i in range(steps-1)], steps, '400-no_outliers-1')\n",
    "    attampt(data, traces, [300 for i in range(steps-1)], steps, '300-no_outliers-1')\n",
    "    attampt(data, traces, [200 for i in range(steps-1)], steps, '200-no_outliers-1')\n",
    "    attampt(data, traces, [150 for i in range(steps-1)], steps, '150-no_outliers-1')\n",
    "    attampt(data, traces, [100 for i in range(steps-1)], steps, '100-no_outliers-1')\n",
    "    attampt(data, traces, [70 for i in range(steps-1)], steps, '70-no_outliers-1')\n",
    "    attampt(data, traces, [50 for i in range(steps-1)], steps, '50-no_outliers-1')\n",
    "    attampt(data, traces, [30 for i in range(steps-1)], steps, '30-no_outliers-1')\n",
    "    attampt(data, traces, [20 for i in range(steps-1)], steps, '20-no_outliers-1')\n",
    "    attampt(data, traces, [10 for i in range(steps-1)], steps, '10-no_outliers-1')\n",
    "    attampt(data, traces, [5 for i in range(steps-1)], steps, '5-no_outliers-1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "get_result_no(data_no_outliers, traces_no_outliers, 20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#data_no_outliers , traces_no_outliers = outlier_remove(f['data'][:10000], f['traces'][:10000],1)\n",
    "#print('\\n')\n",
    "#get_result_no(data_no_outliers, traces_no_outliers, 20)\n",
    "\n",
    "initials = [1623]\n",
    "rates = [0.9 - 0.1*i  for i in range(9)]\n",
    "for initial in initials:\n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(88):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(data_no_outliers, traces_no_outliers, POIs, len(POIs)+1, f'{initial}-{rate}-no_outliers-1-reference')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_result_replace(data, traces, steps, threshold):\n",
    "    #attampt(data, traces, [500 for i in range(steps-1)], steps, f'500-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [400 for i in range(steps-1)], steps, f'400-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [300 for i in range(steps-1)], steps, f'300-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [200 for i in range(steps-1)], steps, f'200-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [150 for i in range(steps-1)], steps, f'150-replace_outliers-{threshold}')\n",
    "    attampt(data, traces, [100 for i in range(steps-1)], steps, f'100-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [70 for i in range(steps-1)], steps, f'70-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [50 for i in range(steps-1)], steps, f'50-replace_outliers-{threshold}')\n",
    "    attampt(data, traces, [30 for i in range(steps-1)], steps, f'30-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [20 for i in range(steps-1)], steps, f'20-replace_outliers-{threshold}')\n",
    "    #attampt(data, traces, [10 for i in range(steps-1)], steps, f'10-replace_outliers-{threshold}')\n",
    "    attampt(data, traces, [5 for i in range(steps-1)], steps, f'5-replace_outliers-{threshold}')\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "outlier number: 330799\n",
      "outlier ratio: 0.0330799\n",
      "traces_new.shape: (10000, 1000)\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "traces_mean_outliers = outlier_replace(traces_ecc_pointer[:10000], 2)\n",
    "print('\\n')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "#get_result_replace(f['data'][:10000], traces_mean_outliers, 20)\n",
    "\n",
    "initials = [1623]\n",
    "rates = [0.9 - 0.1*i  for i in range(9)]\n",
    "#rates = [0.9]\n",
    "for initial in initials:\n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(88):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(data_ecc_pointer[:10000], traces_ecc_pointer[:10000], POIs, len(POIs)+1, f'{initial}-{rate}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [],
   "source": [
    "get_result(data_ecc_pointer[:10000], traces_mean_outliers, 20, 'replace_outliers-2')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_result_removed(data, traces, steps, threshold):\n",
    "    n_traces = traces.shape[0]\n",
    "    n_points = traces.shape[1]\n",
    "\n",
    "    labels_all = np.zeros((n_traces, n_points))\n",
    "    \n",
    "\n",
    "    # apply kmeans to all points of one timing, determine the label of each point\n",
    "    for i in range(traces.shape[1]):\n",
    "        kmeans_cluster = KMeans(n_clusters=2, random_state=0).fit(traces[:, i].reshape(-1, 1))\n",
    "        labels_all[:,i] = kmeans_cluster.labels_\n",
    "\n",
    "    #attampt_single(data, traces, [500 for i in range(steps-1)], steps, f'500-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [400 for i in range(steps-1)], steps, f'400-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [300 for i in range(steps-1)], steps, f'300-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [200 for i in range(steps-1)], steps, f'200-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [150 for i in range(steps-1)], steps, f'150-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [100 for i in range(steps-1)], steps, f'100-no_outliers-{threshold}', labels_all)\n",
    "    #ttampt_single(data, traces, [70 for i in range(steps-1)], steps, f'70-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [50 for i in range(steps-1)], steps, f'50-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [30 for i in range(steps-1)], steps, f'30-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [20 for i in range(steps-1)], steps, f'20-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [10 for i in range(steps-1)], steps, f'10-no_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [5 for i in range(steps-1)], steps, f'5-no_outliers-{threshold}', labels_all)\n",
    "\n",
    "    attampt_single(data, traces, [500 for i in range(steps-1)], steps, '500', labels_all)\n",
    "    #attampt_single(data, traces, [400 for i in range(steps-1)], steps, '400', labels_all)\n",
    "    #attampt_single(data, traces, [300 for i in range(steps-1)], steps, '300', labels_all)\n",
    "    #ttampt_single(data, traces, [200 for i in range(steps-1)], steps, '200', labels_all)\n",
    "    attampt_single(data, traces, [150 for i in range(steps-1)], steps, '100', labels_all)\n",
    "    #attampt_single(data, traces, [100 for i in range(steps-1)], steps, '70', labels_all)\n",
    "    #attampt_single(data, traces, [70 for i in range(steps-1)], steps, '50', labels_all)\n",
    "    #attampt_single(data, traces, [50 for i in range(steps-1)], steps, '40', labels_all)\n",
    "    attampt_single(data, traces, [30 for i in range(steps-1)], steps, '30', labels_all)\n",
    "    #attampt_single(data, traces, [20 for i in range(steps-1)], steps, '20', labels_all)\n",
    "    #attampt_single(data, traces, [10 for i in range(steps-1)], steps, '10', labels_all)\n",
    "    #attampt_single(data, traces, [5 for i in range(steps-1)], steps, '', labels_all)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.\n",
      "  # Remove the CWD from sys.path while we load stuff.\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    }
   ],
   "source": [
    "\n",
    "\n",
    "#data_no_outliers , traces_no_outliers = outlier_remove(f['data'][:10000], f['traces'][:10000],1.1)\n",
    "print('\\n')\n",
    "get_result_removed(f['data'][:10000], f['traces'][:10000], 20, 0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "outlier number: 749175\n",
      "outlier ratio: 0.04615988909426987\n",
      "traces_new.shape: (10000, 1623)\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.\n",
      "  # Remove the CWD from sys.path while we load stuff.\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    }
   ],
   "source": [
    "traces_mean_outliers = outlier_replace(f['traces'][:10000], 2)\n",
    "print('\\n')\n",
    "get_result_replace(f['data'][:10000], traces_mean_outliers, 20, 2)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_result_replace(data, traces, steps, threshold):\n",
    "    n_traces = traces.shape[0]\n",
    "    n_points = traces.shape[1]\n",
    "\n",
    "    labels_all = np.zeros((n_traces, n_points))\n",
    "    \n",
    "\n",
    "    # apply kmeans to all points of one timing, determine the label of each point\n",
    "    for i in range(traces.shape[1]):\n",
    "        kmeans_cluster = KMeans(n_clusters=2, random_state=0).fit(traces[:, i].reshape(-1, 1))\n",
    "        labels_all[:,i] = kmeans_cluster.labels_\n",
    "\n",
    "    attampt_single(data, traces, [500 for i in range(steps-1)], steps, f'500-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [400 for i in range(steps-1)], steps, f'400-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [300 for i in range(steps-1)], steps, f'300-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [200 for i in range(steps-1)], steps, f'200-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [150 for i in range(steps-1)], steps, f'150-replace_outliers-{threshold}', labels_all)\n",
    "    attampt_single(data, traces, [100 for i in range(steps-1)], steps, f'100-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [70 for i in range(steps-1)], steps, f'70-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [50 for i in range(steps-1)], steps, f'50-replace_outliers-{threshold}', labels_all)\n",
    "    attampt_single(data, traces, [30 for i in range(steps-1)], steps, f'30-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [20 for i in range(steps-1)], steps, f'20-replace_outliers-{threshold}', labels_all)\n",
    "    #attampt_single(data, traces, [10 for i in range(steps-1)], steps, f'10-replace_outliers-{threshold}', labels_all)\n",
    "    attampt_single(data, traces, [5 for i in range(steps-1)], steps, f'5-replace_outliers-{threshold}', labels_all)\n",
    "    \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.\n",
      "  # Remove the CWD from sys.path while we load stuff.\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    }
   ],
   "source": [
    "get_result_replace(f['data'][:10000], traces_mean_outliers, 20, 2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "outlier number: 2137379\n",
      "outlier ratio: 0.13169309919901417\n",
      "traces_new.shape: (10000, 1623)\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:10: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (2). Possibly due to duplicate points in X.\n",
      "  # Remove the CWD from sys.path while we load stuff.\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n",
      "/usr/local/home/yizhu/.local/lib/python3.6/site-packages/ipykernel_launcher.py:41: RuntimeWarning: invalid value encountered in double_scalars\n"
     ]
    }
   ],
   "source": [
    "traces_mean_outliers = outlier_replace(f['traces'][:10000], 1.5)\n",
    "print('\\n')\n",
    "get_result_replace(f['data'][:10000], traces_mean_outliers, 20, 1.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "initials = [1623]\n",
    "rates = rates = [0.9]\n",
    "for initial in initials:\n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(88):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(f['data'][:10000], traces_mean_outliers, POIs, len(POIs)+1, f'{initial}-{rate}-replace_outliers-2')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "data_no_outliers , traces_no_outliers = outlier_remove(f['data'][:10000], f['traces'][:10000],1.5)\n",
    "print('\\n')\n",
    "#get_result_no(data_no_outliers, traces_no_outliers, 20)\n",
    "\n",
    "initials = [1623,500,300,200,150,100,70,50,30,20,10,5]\n",
    "rates = [0.9 - 0.1*i  for i in range(9)]\n",
    "for initial in initials:\n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(38):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(data_no_outliers, traces_no_outliers, POIs, len(POIs)+1, f'{initial}-{rate}-no_outliers-1.5')\n",
    "\n",
    "\n",
    "\n",
    "traces_mean_outliers = outlier_replace(f['traces'][:10000], 1.5)\n",
    "print('\\n')\n",
    "#get_result_replace(f['data'][:10000], traces_mean_outliers, 20)\n",
    "\n",
    "initials = [1623,500,300,200,150,100,70,50,30,20,10,5]\n",
    "rates = [0.9 - 0.1*i  for i in range(9)]\n",
    "for initial in initials:\n",
    "    for rate in rates:\n",
    "        POIs = [initial]\n",
    "        for i in range(38):\n",
    "            POI = int(initial * rate ** (i+1) )\n",
    "\n",
    "            if POI > 0:\n",
    "                POIs.append(POI)\n",
    "            else:\n",
    "                continue\n",
    "\n",
    "        if POIs:\n",
    "            attampt(f['data'][:10000], traces_mean_outliers, POIs, len(POIs)+1, f'{initial}-{rate}-replace_outliers-1.5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "POI_numbers = [int(f['traces'].shape[1] * 0.8**(i+1)) for i in range(30)]\n",
    "print(POI_numbers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "attampt(f['data'][:5000], f['traces'][:5000], POI_numbers, 30)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
